database:
  host: localhost
  port: 6024
  user: persrag
  password: ""  # Set via DB_PASSWORD environment variable
  dbname: rag
  collection: rag_documents

rag:
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: text-embedding-3-small
  chat_model: gpt-4o-mini
  top_k: 4
  use_enhanced_retrieval: true  # Enable HyDE + hybrid search + reranking
  reranker_model: cross-encoder/ms-marco-MiniLM-L-6-v2
  hybrid_vector_weight: 0.5  # 0.5 = equal weight for vector and BM25
